### ISSUE TITLE
Can't Package Solution

### ISSUE THREAD

**Issue by MrDrSushi** [Zerg00s/sp-migration-dashboard#3]
Hi, first of all, thanks for sharing, pretty good solution!

I've downloaded and compiled, can get it running with **gulp serve** but when I try to **gulp build --ship** and later try to **gulp package-solution --ship** it fails (quite a long list of error messages).

I've tried under NodeJS 10.22.0 and 10.13.0 - both aren't working, could you please provide more information on how to sucessfully build and package for deployment for production?

See screen shots below:

<img width="1312" alt="error-1" src="https://user-images.githubusercontent.com/10159701/109120576-01e79800-77ab-11eb-84a7-ac6fd9a5b62d.png">
<img width="1346" alt="error-2 (1 of 2)" src="https://user-images.githubusercontent.com/10159701/109120581-0318c500-77ab-11eb-91c9-23faf9c9983f.png">
<img width="1349" alt="error-2 (2 of 2)" src="https://user-images.githubusercontent.com/10159701/109120584-03b15b80-77ab-11eb-8d72-78438e1dbf12.png">

**Comment by Zerg00s** [comment]
@MrDrSushi I was able to replicate the same error. Thank you for the screenshots. They were very useful.

The node versions you mentioned are supported and not an issue.

The reason you are getting the error is that you are missing an important step. The `gulp bundle --ship` step. This is the correct way of building SPFx projects including the Migration Dashboard. This should definitely work if you try it:

```
gulp clean 
gulp bundle --ship
gulp package-solution --ship
```

I personally use a one-liner that combines all three commands in a single one:
```
gulp clean ; gulp bundle --ship ; gulp package-solution --ship
```

If you noticed, I skip the `gulp build`. This is because `gulp bundle` includes it.

**Comment by MrDrSushi** [comment]
Hey mate, thanks for the feedback!

I'm pretty sure I've tried bundling among other things , not sure now but I trust your words much more than my memory :)

thanks for your help!
